### ISSUE TITLE
Reason for duplicating the kinematics_solver key in both groups?

### ISSUE THREAD

**Issue by gavanderhoorn** [marip8/sampling_kinematics_plugin#4]
Tbf I haven't read the code yet, but I was wondering why the configuration needs to duplicate the solver entry in the `ext_` map: could the value of `robot_group` not be used to retrieve the value of `kinematics_solver`?

```yaml
ext_axis_manipulator:
  [..]
  robot_group: manipulator
  robot_kinematics_solver: ur_kinematics/UR5KinematicsPlugin
manipulator:
  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
  [..]
```

Avoiding duplication would be good: one less place to make mistakes.
